FROM node:22-alpine as build-stage
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps

COPY frontend/ ./

ENV VITE_API_URL=/api

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build-stage /app/build /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]